/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Expences.java
 *
 * Created on Apr 15, 2010, 11:27:39 PM
 */

package Chathura;

import Imal.playSond;
import Imal.validate1;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author Chatura
 */
public class Expences extends javax.swing.JFrame {

    /** Creates new form Expences */
    public Expences() {
        initComponents();


        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tFTotalRepairs = new javax.swing.JTextField();
        tFTotalBudget = new javax.swing.JTextField();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        tFDepartmentRepairs = new javax.swing.JTextField();
        tFMinorConstructions = new javax.swing.JTextField();
        tFMajorConstructions = new javax.swing.JTextField();
        tFAreaRepairs = new javax.swing.JTextField();
        tFTotalConstructions = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tFTotalRepairs1 = new javax.swing.JTextField();
        tFTotalBudget1 = new javax.swing.JTextField();
        tFDepartmentRepairs1 = new javax.swing.JTextField();
        tFMinorConstructions1 = new javax.swing.JTextField();
        tFMajorConstructions1 = new javax.swing.JTextField();
        tFAreaRepairs1 = new javax.swing.JTextField();
        tFTotalConstructions1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Year");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText("Total Budget Expense ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setText("Total Expense for Constructions");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setText("Expenses for Minor constructions");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel8.setText("Expenses for Major constructions");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setText("Total Expenses for Repairs");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel9.setText("Expenses of Judicial areas");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel6.setText("Expenses of Department Repairs");

        tFTotalRepairs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tFTotalRepairsKeyReleased(evt);
            }
        });

        tFTotalBudget.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tFTotalBudgetKeyReleased(evt);
            }
        });

        tFDepartmentRepairs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tFDepartmentRepairsKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tFDepartmentRepairsKeyTyped(evt);
            }
        });

        tFMinorConstructions.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tFMinorConstructionsKeyReleased(evt);
            }
        });

        tFMajorConstructions.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tFMajorConstructionsKeyReleased(evt);
            }
        });

        tFAreaRepairs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFAreaRepairsActionPerformed(evt);
            }
        });
        tFAreaRepairs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tFAreaRepairsKeyReleased(evt);
            }
        });

        tFTotalConstructions.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tFTotalConstructionsKeyReleased(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Andalus", 0, 28));
        jLabel18.setText("Current Budget Expenses");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chathura/plus_16.png"))); // NOI18N
        jButton2.setText("View Details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chathura/Refresh_16x16.png"))); // NOI18N
        jButton5.setText("Remaining");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addComponent(jLabel8)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(51, 51, 51))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(tFDepartmentRepairs, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(tFAreaRepairs, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(tFMajorConstructions, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                                            .addComponent(tFMinorConstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(28, 28, 28))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tFTotalConstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tFTotalRepairs, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(tFTotalBudget, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
                        .addGap(20, 20, 20)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jYearChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tFTotalBudget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tFTotalConstructions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tFMinorConstructions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tFMajorConstructions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tFTotalRepairs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tFAreaRepairs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tFDepartmentRepairs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(27, 27, 27))
        );

        jLabel1.setFont(new java.awt.Font("Andalus", 0, 28));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Chathura/Refresh_32x32.png"))); // NOI18N
        jLabel1.setText("Current Budget Details");

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel11.setText("Total Budget Remaining ");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel12.setText("Total Remaining for Constructions");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel13.setText("Remaining for Minor constructions");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel14.setText("Remaining for Major constructions");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel15.setText("Total Remaining for Repairs");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel16.setText("Remaining for Judicial areas");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel17.setText("Remaining for Department use");

        tFTotalRepairs1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tFTotalRepairs1KeyReleased(evt);
            }
        });

        tFTotalBudget1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tFTotalBudget1KeyReleased(evt);
            }
        });

        tFDepartmentRepairs1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tFDepartmentRepairs1KeyReleased(evt);
            }
        });

        tFMinorConstructions1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tFMinorConstructions1KeyReleased(evt);
            }
        });

        tFMajorConstructions1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tFMajorConstructions1KeyReleased(evt);
            }
        });

        tFAreaRepairs1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tFAreaRepairs1KeyReleased(evt);
            }
        });

        tFTotalConstructions1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tFTotalConstructions1KeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Andalus", 0, 28));
        jLabel10.setText("Remaining of the Budget");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 419, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addGap(45, 45, 45)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tFMajorConstructions1))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addGap(18, 18, 18)
                                            .addComponent(tFMinorConstructions1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addGap(44, 44, 44)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(24, 24, 24)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tFAreaRepairs1)
                                        .addComponent(tFDepartmentRepairs1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tFTotalBudget1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tFTotalConstructions1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(tFTotalRepairs1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tFTotalBudget1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tFTotalConstructions1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tFMinorConstructions1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tFMajorConstructions1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tFTotalRepairs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tFAreaRepairs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tFDepartmentRepairs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-956)/2, (screenSize.height-603)/2, 956, 603);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
   playSond.ButtonClick();
        int year = jYearChooser1.getValue();
        String year1 = String.valueOf(year);

        try {

         Connection con = DB.getMyConnection();
         Statement st = con.createStatement();
         ResultSet rs =  st.executeQuery("SELECT AreaRepairs FROM budget WHERE Year = '"+year1+"' ");



           while ((rs.next())) {

            tFAreaRepairs.setText((rs.getString("AreaRepairs")));

            }




        } catch (Exception e) {

            System.out.println(e);
        }

        try {

         Connection con = DB.getMyConnection();
         Statement st = con.createStatement();
         ResultSet rs =  st.executeQuery("SELECT MajorConstructions FROM budget WHERE Year = '"+year1+"' ");



           while ((rs.next())) {

            tFMajorConstructions.setText((rs.getString("MajorConstructions")));

            }




        } catch (Exception e) {

            System.out.println(e);
        }

        try {

         Connection con = DB.getMyConnection();
         Statement st = con.createStatement();
         ResultSet rs =  st.executeQuery("SELECT SUM(AmountPaid) as tot FROM project WHERE Year = '"+year1+"' and scale = 'Small Scale Construction'  ");



           while ((rs.next())) {
               
            tFMinorConstructions.setText((rs.getString("tot")));

            }



        } catch (Exception e) {

            System.out.println(e);
        }

      /*  try {

         Connection con = DB.getMyConnection();
         Statement st = con.createStatement();
         ResultSet rs =  st.executeQuery("SELECT SUM(AmountPaid) as tot FROM project WHERE Year = '"+year1+"' and scale = 'large'  ");



           while ((rs.next())) {

            tFMajorConstructions.setText((rs.getString("tot")));

            }



        } catch (Exception e) {

            System.out.println(e);
        }*/

         try {

         Connection con = DB.getMyConnection();
         Statement st = con.createStatement();
         ResultSet rs =  st.executeQuery("SELECT SUM(AmountPaid) as tot FROM project WHERE Year = '"+year1+"' and scale = 'Repairs'  ");



           while ((rs.next())) {

            tFDepartmentRepairs.setText((rs.getString("tot")));

            }



        } catch (Exception e) {

            System.out.println(e);
        }


         String minorConstructions = tFMinorConstructions.getText();
         String majorConstructions = tFMajorConstructions.getText();
         String departmentRepairs = tFDepartmentRepairs.getText();
         String areaRepairs = tFAreaRepairs.getText();


         double t1 = Double.parseDouble(minorConstructions);
         double t2 = Double.parseDouble(majorConstructions);
         double t3 = Double.parseDouble(departmentRepairs);
         double t5 = Double.parseDouble(areaRepairs);

         double t4 = t1 + t2 ;

         String s1 = String.valueOf(t4);
         tFTotalConstructions.setText(s1);

         double t6 = t3 + t5;
         String s2 = String.valueOf(t6);
         tFTotalRepairs.setText(s2);

         double t7 = t4 + t6;
         String s3 = String.valueOf(t7);
         tFTotalBudget.setText(s3);



         


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    playSond.ButtonClick();
        int year = jYearChooser1.getValue();
        String year1 = String.valueOf(year);

         String s1 = "0" , s2 = "0" , s3 = "0" , s4 = "0" , s5 = "0" , s6 = "0" , s7 = "0";
    try {

         Connection con = DB.getMyConnection();
         Statement st = con.createStatement();
         ResultSet rs =  st.executeQuery("SELECT * FROM budget WHERE Year = '"+year1+"' ");



           if ((rs.next())) {



               s1 = rs.getString("TotalBudget");
               s2 = rs.getString("TotalConstructions");
               s3 = rs.getString("MajorConstructions");
               s4 = rs.getString("MinorConstructions");
               s5 = rs.getString("TotalRepairs");
               s6 = rs.getString("AreaRepairs");
               s7 = rs.getString("DepartmentRepairs");


            }

        } catch (Exception e) {

            System.out.println(e);
        }

        String w1 = tFTotalBudget.getText();
        String w2 = tFTotalConstructions.getText();
        String w3 = tFMinorConstructions.getText();
        String w4 = tFMajorConstructions.getText();
        String w5 = tFTotalRepairs.getText();
        String w6 = tFAreaRepairs.getText();
        String w7 = tFDepartmentRepairs.getText();

        double t1 , t2 , t3 , t4 , t5 , t6 , t7;
        double d1 , d2 , d3 , d4 , d5 , d6 , d7;
        double h1 , h2 , h3 , h4 , h5 , h6 , h7;

        t1 = Double.parseDouble(s1);
        t2 = Double.parseDouble(s2);
        t3 = Double.parseDouble(s3);
        t4 = Double.parseDouble(s4);
        t5 = Double.parseDouble(s5);
        t6 = Double.parseDouble(s6);
        t7 = Double.parseDouble(s7);
        
        d1 = Double.parseDouble(w1);
        d2 = Double.parseDouble(w2);
        d3 = Double.parseDouble(w3);
        d4 = Double.parseDouble(w4);
        d5 = Double.parseDouble(w5);
        d6 = Double.parseDouble(w6);
        d7 = Double.parseDouble(w7);
        
        h1 = t1 - d1;
        h2 = t2 - d2;
        h3 = t4 - d3;
        h4 = t3 - d4;//major
        h5 = t5 - d5;
        h6 = t6 - d6;
        h7 = t7 - d7;

        tFTotalBudget1.setText(String.valueOf(h1));
        tFTotalConstructions1.setText(String.valueOf(h2));
        tFMinorConstructions1.setText(String.valueOf(h3));
        tFMajorConstructions1.setText(String.valueOf(h4));
        tFTotalRepairs1.setText(String.valueOf(h5));
        tFAreaRepairs1.setText(String.valueOf(h6));
        tFDepartmentRepairs1.setText(String.valueOf(h7));

    }//GEN-LAST:event_jButton5ActionPerformed

    private void tFAreaRepairsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFAreaRepairsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tFAreaRepairsActionPerformed

    private void tFTotalBudgetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFTotalBudgetKeyReleased
       tFTotalBudget.setText((new validate1().mytext(tFTotalBudget,evt)));
    }//GEN-LAST:event_tFTotalBudgetKeyReleased

    private void tFTotalConstructionsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFTotalConstructionsKeyReleased
       tFTotalConstructions.setText((new validate1().mytext(tFTotalConstructions,evt)));
    }//GEN-LAST:event_tFTotalConstructionsKeyReleased

    private void tFMinorConstructionsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFMinorConstructionsKeyReleased
       tFMinorConstructions.setText((new validate1().mytext(tFMinorConstructions,evt)));
    }//GEN-LAST:event_tFMinorConstructionsKeyReleased

    private void tFMajorConstructionsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFMajorConstructionsKeyReleased
      tFMajorConstructions.setText((new validate1().mytext(tFMajorConstructions,evt)));
    }//GEN-LAST:event_tFMajorConstructionsKeyReleased

    private void tFTotalRepairsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFTotalRepairsKeyReleased
      tFTotalRepairs.setText((new validate1().mytext(tFTotalRepairs,evt)));
    }//GEN-LAST:event_tFTotalRepairsKeyReleased

    private void tFAreaRepairsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFAreaRepairsKeyReleased
      tFAreaRepairs.setText((new validate1().mytext(tFAreaRepairs,evt)));
    }//GEN-LAST:event_tFAreaRepairsKeyReleased

    private void tFDepartmentRepairsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFDepartmentRepairsKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_tFDepartmentRepairsKeyTyped

    private void tFDepartmentRepairsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFDepartmentRepairsKeyReleased
       tFDepartmentRepairs.setText((new validate1().mytext(tFDepartmentRepairs,evt)));
    }//GEN-LAST:event_tFDepartmentRepairsKeyReleased

    private void tFTotalBudget1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFTotalBudget1KeyReleased
       tFTotalBudget1.setText((new validate1().mytext(tFTotalBudget1,evt)));
    }//GEN-LAST:event_tFTotalBudget1KeyReleased

    private void tFTotalConstructions1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFTotalConstructions1KeyReleased
        tFTotalConstructions1.setText((new validate1().mytext(tFTotalConstructions1,evt)));
    }//GEN-LAST:event_tFTotalConstructions1KeyReleased

    private void tFMinorConstructions1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFMinorConstructions1KeyReleased
       tFMinorConstructions1.setText((new validate1().mytext(tFMinorConstructions1,evt)));
    }//GEN-LAST:event_tFMinorConstructions1KeyReleased

    private void tFMajorConstructions1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFMajorConstructions1KeyReleased
       tFMajorConstructions1.setText((new validate1().mytext(tFMajorConstructions1,evt)));
    }//GEN-LAST:event_tFMajorConstructions1KeyReleased

    private void tFTotalRepairs1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFTotalRepairs1KeyReleased
     tFTotalRepairs1.setText((new validate1().mytext(tFTotalRepairs1,evt)));
    }//GEN-LAST:event_tFTotalRepairs1KeyReleased

    private void tFAreaRepairs1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFAreaRepairs1KeyReleased
       tFAreaRepairs1.setText((new validate1().mytext(tFAreaRepairs1,evt)));
    }//GEN-LAST:event_tFAreaRepairs1KeyReleased

    private void tFDepartmentRepairs1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFDepartmentRepairs1KeyReleased
        tFDepartmentRepairs1.setText((new validate1().mytext(tFDepartmentRepairs1,evt)));
    }//GEN-LAST:event_tFDepartmentRepairs1KeyReleased

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Expences().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private javax.swing.JTextField tFAreaRepairs;
    private javax.swing.JTextField tFAreaRepairs1;
    private javax.swing.JTextField tFDepartmentRepairs;
    private javax.swing.JTextField tFDepartmentRepairs1;
    private javax.swing.JTextField tFMajorConstructions;
    private javax.swing.JTextField tFMajorConstructions1;
    private javax.swing.JTextField tFMinorConstructions;
    private javax.swing.JTextField tFMinorConstructions1;
    private javax.swing.JTextField tFTotalBudget;
    private javax.swing.JTextField tFTotalBudget1;
    private javax.swing.JTextField tFTotalConstructions;
    private javax.swing.JTextField tFTotalConstructions1;
    private javax.swing.JTextField tFTotalRepairs;
    private javax.swing.JTextField tFTotalRepairs1;
    // End of variables declaration//GEN-END:variables

}
