/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Request1.java
 *
 * Created on 13-Apr-2010, 16:36:16
 */

package Sajeewa;

import Imal.playSond;
import de.javasoft.plaf.synthetica.SyntheticaBlackEyeLookAndFeel;
import java.sql.ResultSet;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.UIManager;


/**
 *
 * @author saj
 */
public class Request1 extends javax.swing.JFrame {
public ResultSet rest ;
int thisYear;
Request2 frame1 = new Request2();
    /** Creates new form Request1 */
    public Request1() {

       
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        yearComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        judicialZoneComboBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        scaleComboBox = new javax.swing.JComboBox();
        showAllButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        ActionPlanButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel6.setFont(new java.awt.Font("Andalus", 0, 28));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sajeewa/Search_32x32.png"))); // NOI18N
        jLabel6.setText("Search For Requests Received");

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        yearComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "2009", "2010", "2011", "2012", "2013", "All" }));
        yearComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText("Please select the year you want to view the request  ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel5.setText("Please select the Judicial Zone you want to search  ");

        judicialZoneComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Anuradapura", "Polonnaruwa", "Colombo", "Gall", "Kandy", "All Judical Zones" }));
        judicialZoneComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                judicialZoneComboBoxActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel7.setText("Select the type of the project");

        scaleComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Large Scale Construction", "Small Scale Constructions", "Repairs", "All" }));
        scaleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scaleComboBoxActionPerformed(evt);
            }
        });

        showAllButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sajeewa/New file.png"))); // NOI18N
        showAllButton.setText("Show All ");
        showAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllButtonActionPerformed(evt);
            }
        });

        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sajeewa/Search_16x16.png"))); // NOI18N
        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yearComboBox, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(scaleComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(judicialZoneComboBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 181, Short.MAX_VALUE)))
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(456, Short.MAX_VALUE)
                .addComponent(showAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(judicialZoneComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scaleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(showAllButton))
                .addGap(20, 20, 20))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sajeewa/right_16.png"))); // NOI18N
        jButton1.setText("View requests from this year");
        jButton1.setIconTextGap(-155);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ActionPlanButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sajeewa/right_16.png"))); // NOI18N
        ActionPlanButton.setText("View action plan for this year");
        ActionPlanButton.setIconTextGap(-160);
        ActionPlanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionPlanButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Or perform a preloaded task please......");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(242, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(29, 29, 29)
                .addComponent(ActionPlanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(330, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ActionPlanButton)
                    .addComponent(jButton1))
                .addGap(18, 18, 18))
        );

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Sajeewa/delete_16.png"))); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jSeparator1)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(605, Short.MAX_VALUE)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cancelButton)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-732)/2, (screenSize.height-578)/2, 732, 578);
    }// </editor-fold>//GEN-END:initComponents

    private void yearComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearComboBoxActionPerformed


//if(x.equals("select")){
//
//}
//if(x.equals("2009")){
//    try {
//          Connection con_req2009 = DB.getCon();
//          Statement state_req2009 = con_req2009.createStatement();
//          ResultSet rset_req2009 = state_req2009.executeQuery("select * from request where ProjectType ='"+x+"%'");
//          rest = rset_req2009;
//            } catch (Exception e) {
//            }
//
//}
// if(x.equals("2010")){
//     test t1 = new test();
//
//
//}
//if(x.equals("2011")){
//     try {
//          Connection con_req2011 = DB.getCon();
//          Statement state_req2011 = con_req2011.createStatement();
//          ResultSet rset_req2011 = state_req2011.executeQuery("select * from request where ProjectType ='"+x+"%'");
//          rest = rset_req2011;
//     } catch (Exception e) {
//            }
//
//}
//if(x.equals("2012")){
//     try {
//         Connection con_req2012  Connection con_req2012 = DB.getCon();
//          Statement state_req2012 = con_req2012.createStatement();
//          ResultSet rset_req2012 = state_req2012.executeQuery("select * from request where ProjectType ='"+x+"%'");
//           rest = rset_req2012;
//            } catch (Exception e) {
//            }
//
//}
//if(x.equals("2013")){
//     try {
//
//          Connection con_req2013 = DB.getCon();
//          Statement state_req2013 = con_req2013.createStatement();
//          ResultSet rset_req2013 = state_req2013.executeQuery("select * from request where ProjectType ='"+x+"%'");
//          rest = rset_req2013;
//            } catch (Exception e) {
//            }
//
//}






        // TODO add your handling code here:
}//GEN-LAST:event_yearComboBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
Calendar cal = Calendar.getInstance();
thisYear = cal.get(Calendar.YEAR);
Request2 frmae3 = new Request2();
frmae3.getYear(String.valueOf(thisYear));
frmae3.setResult1();
frmae3.setVisible(true);
this.setVisible(false);

        //  test.getreqform().setVisible(true);
}//GEN-LAST:event_jButton1ActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
     playSond.ButtonClick();
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
       playSond.ButtonClick();
        playSond.ButtonClick();
        String year, judicialZone, scale;
        year = yearComboBox.getSelectedItem().toString();
        judicialZone = judicialZoneComboBox.getSelectedItem().toString();
        scale = scaleComboBox.getSelectedItem().toString();
      if(year.equals("Select") & judicialZone.equals("Select")& scale.equals("Select")){
        
          JOptionPane.showMessageDialog(null, "Please select before you search");
          }
        else if(year.equals("Select")){

            JOptionPane.showMessageDialog(null, "Please select the year you want to search for requests");
        }
        else if(judicialZone.equals("Select")){

            JOptionPane.showMessageDialog(null, "Please select the judicial Zone you want to search for requests");
        }
        else if(scale.equals("Select")){

            JOptionPane.showMessageDialog(null, "Please select the scale of the request you want to view");
        }
        else{
 frame1.getYear(year);
        frame1.getJZone(judicialZone);
        frame1.getScale(scale);

        System.out.println(year+judicialZone+scale);
        
        frame1.setResult();
        frame1.setVisible(true);
        this.dispose();
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void judicialZoneComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judicialZoneComboBoxActionPerformed
 

    }//GEN-LAST:event_judicialZoneComboBoxActionPerformed

    private void scaleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scaleComboBoxActionPerformed
    
    }//GEN-LAST:event_scaleComboBoxActionPerformed

    private void showAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllButtonActionPerformed
playSond.ButtonClick();
        Request2 frame2 = new Request2();
 frame2.getYear("All");
 frame2.getJZone("All Judicial Zones");
 frame2.getScale("All");
  System.out.println("hi hi");
   
        frame2.setAllResults();
        frame2.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_showAllButtonActionPerformed

    private void ActionPlanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionPlanButtonActionPerformed
playSond.ButtonClick();
        Calendar cal = Calendar.getInstance();
thisYear = cal.get(Calendar.YEAR);

ActionPlan ap = new ActionPlan();
ap.getYear(thisYear);
ap.setResult();
ap.setVisible(true);



    }//GEN-LAST:event_ActionPlanButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {

         try {
        UIManager.setLookAndFeel(new SyntheticaBlackEyeLookAndFeel());


        }
        catch (Exception e) {


        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Request1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActionPlanButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox judicialZoneComboBox;
    private javax.swing.JComboBox scaleComboBox;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton showAllButton;
    private javax.swing.JComboBox yearComboBox;
    // End of variables declaration//GEN-END:variables

}
