/*
 * ViewBillDetails.java
 *
 * Created on April 10, 2010, 6:26 PM
 */

package billing;

import Imal.playSond;
import de.javasoft.plaf.synthetica.SyntheticaBlackEyeLookAndFeel;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  Chatura
 */
public class ViewBillDetails extends javax.swing.JFrame {
    String cb;
    String tb;

    /** Creates new form ViewBillDetails */
    public ViewBillDetails() {
        initComponents();
        
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cbSearch = new javax.swing.JComboBox();
        lBCriteria = new javax.swing.JLabel();
        tFCriteria = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tBSearch = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Bill Details");

        jLabel1.setFont(new java.awt.Font("Andalus", 0, 28));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billing/clipboard_32.png"))); // NOI18N
        jLabel1.setText("View Bill Details");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Search by");
        jLabel2.setIconTextGap(8);

        cbSearch.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Plese select the criteria", "Project ID", "Contractor Name", "Bill No", "Bill Title" }));
        cbSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSearchActionPerformed(evt);
            }
        });

        lBCriteria.setFont(new java.awt.Font("Tahoma", 1, 12));
        lBCriteria.setText("Searching Criteria");

        tFCriteria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tFCriteriaActionPerformed(evt);
            }
        });
        tFCriteria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tFCriteriaKeyReleased(evt);
            }
        });

        tBSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Project ID", "Contractor ID", "Bill No", "Bill Name", "Final Amount"
            }
        ));
        tBSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tBSearchMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tBSearch);
        tBSearch.getColumnModel().getColumn(2).setMinWidth(60);
        tBSearch.getColumnModel().getColumn(2).setPreferredWidth(60);
        tBSearch.getColumnModel().getColumn(2).setMaxWidth(60);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billing/right_16.png"))); // NOI18N
        jButton1.setText("Next");
        jButton1.setIconTextGap(-50);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/billing/delete_16.png"))); // NOI18N
        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                            .addComponent(cbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lBCriteria, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tFCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(176, 176, 176))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE))
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lBCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tFCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-562)/2, (screenSize.height-551)/2, 562, 551);
    }// </editor-fold>//GEN-END:initComponents

private void tFCriteriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tFCriteriaActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tFCriteriaActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
playSond.ButtonClick();
    BillInfo bi = new BillInfo();
    bi.getID(tb);
    bi.setVisible(true);
    dispose();

}//GEN-LAST:event_jButton1ActionPerformed

private void cbSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSearchActionPerformed
cb = (String) cbSearch.getSelectedItem();
lBCriteria.setText(cb);
  try {

         Connection con = DB.getMyConnection();
         Statement st = con.createStatement();
         ResultSet rs =  st.executeQuery("SELECT * FROM bill_detail ");

         DefaultTableModel df = (DefaultTableModel) tBSearch.getModel();
         df.setRowCount(0);

           while ((rs.next())) {
                Vector v = new Vector();
                v.add(rs.getString("ProjectID"));
                v.add(rs.getString("ContractorID"));
                v.add(rs.getString("BillNo"));
                v.add(rs.getString("BillTitle"));
                v.add(rs.getString("FinalAmount"));

               df.addRow(v);

            }

        } catch (Exception e) {

            System.out.println("HI"+e);
        }
}//GEN-LAST:event_cbSearchActionPerformed

private void tFCriteriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tFCriteriaKeyReleased
    String search = tFCriteria.getText();

    if(cb.equals("Project ID")){

        try {

         Connection con = DB.getMyConnection();
         Statement st = con.createStatement();
         ResultSet rs =  st.executeQuery("SELECT * FROM bill_detail WHERE ProjectID like '"+search+"%' ");

         DefaultTableModel df = (DefaultTableModel) tBSearch.getModel();
         df.setRowCount(0);

           while ((rs.next())) {
                Vector v = new Vector();
                v.add(rs.getString("ProjectID"));
                v.add(rs.getString("ContractorID"));
                v.add(rs.getString("BillNo"));
                v.add(rs.getString("BillTitle"));
                v.add(rs.getString("FinalAmount"));

               df.addRow(v);

            }

        } catch (Exception e) {

            System.out.println(e);
        }


    }

    if(cb.equals("Contractor Name")){

        try {

         Connection con = DB.getMyConnection();
         Statement st = con.createStatement();
         ResultSet rs =  st.executeQuery("SELECT * FROM bill_detail WHERE ContractorID like '"+search+"%' ");

         DefaultTableModel df = (DefaultTableModel) tBSearch.getModel();
         df.setRowCount(0);

           while ((rs.next())) {
                Vector v = new Vector();
                v.add(rs.getString("ProjectID"));
                v.add(rs.getString("ContractorID"));
                v.add(rs.getString("BillNo"));
                v.add(rs.getString("BillTitle"));
                v.add(rs.getString("FinalAmount"));

               df.addRow(v);

            }

        } catch (Exception e) {

            System.out.println(e);
        }


    }
    if(cb.equals("Bill No")){

        try {

         Connection con = DB.getMyConnection();
         Statement st = con.createStatement();
         ResultSet rs =  st.executeQuery("SELECT * FROM bill_detail WHERE BillNo like '"+search+"%' ");

         DefaultTableModel df = (DefaultTableModel) tBSearch.getModel();
         df.setRowCount(0);

           while ((rs.next())) {
                Vector v = new Vector();
                v.add(rs.getString("ProjectID"));
                v.add(rs.getString("ContractorID"));
                v.add(rs.getString("BillNo"));
                v.add(rs.getString("BillTitle"));
                v.add(rs.getString("FinalAmount"));

               df.addRow(v);

            }

        } catch (Exception e) {

            System.out.println(e);
        }


    }
    if(cb.equals("Bill Title")){

        try {

         Connection con = DB.getMyConnection();
         Statement st = con.createStatement();
         ResultSet rs =  st.executeQuery("SELECT * FROM bill_detail WHERE BillTitle like '"+search+"%' ");

         DefaultTableModel df = (DefaultTableModel) tBSearch.getModel();
         df.setRowCount(0);

           while ((rs.next())) {
                Vector v = new Vector();
                v.add(rs.getString("ProjectID"));
                v.add(rs.getString("ContractorID"));
                v.add(rs.getString("BillNo"));
                v.add(rs.getString("BillTitle"));
                v.add(rs.getString("FinalAmount"));

               df.addRow(v);

            }

        } catch (Exception e) {

            System.out.println(e);
        }


    }


}//GEN-LAST:event_tFCriteriaKeyReleased

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
playSond.ButtonClick();
    dispose();
}//GEN-LAST:event_jButton2ActionPerformed

private void tBSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tBSearchMouseClicked
tb =    (String) tBSearch.getValueAt(tBSearch.getSelectedRow(), 2);
    System.out.println(tb);
}//GEN-LAST:event_tBSearchMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        
        try {
            
            UIManager.setLookAndFeel(new SyntheticaBlackEyeLookAndFeel());
            
        } catch (Exception e) {
            
            System.out.println(e);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBillDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lBCriteria;
    private javax.swing.JTable tBSearch;
    private javax.swing.JTextField tFCriteria;
    // End of variables declaration//GEN-END:variables

}
